<?php

declare(strict_types=1);

namespace Roots\Substrate\Mcp\Tools\Acorn;

use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[IsReadOnly]
class ListAssets extends Tool
{
    /**
     * The tool's description.
     */
    protected string $description = 'List all assets from the Vite manifest, including JavaScript, CSS, and other compiled assets from the Sage theme.';

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        $themePath = get_stylesheet_directory();
        $publicPath = $themePath.'/public';

        // Check for Vite manifest
        $manifestPath = $publicPath.'/build/manifest.json';
        $entrypointsPath = $publicPath.'/build/entrypoints.json';

        $result = [
            'build_tool' => 'vite',
            'manifest_path' => null,
            'entrypoints' => [],
            'assets' => [],
        ];

        // Read manifest.json
        if (file_exists($manifestPath)) {
            $result['manifest_path'] = str_replace($themePath.'/', '', $manifestPath);
            $manifest = json_decode(file_get_contents($manifestPath), true);

            if (is_array($manifest)) {
                foreach ($manifest as $source => $data) {
                    $result['assets'][$source] = [
                        'source' => $source,
                        'file' => $data['file'] ?? null,
                        'css' => $data['css'] ?? [],
                        'is_entry' => $data['isEntry'] ?? false,
                    ];
                }
            }
        }

        // Read entrypoints.json
        if (file_exists($entrypointsPath)) {
            $entrypoints = json_decode(file_get_contents($entrypointsPath), true);

            if (is_array($entrypoints)) {
                $result['entrypoints'] = $entrypoints;
            }
        }

        // Check for theme.json (generated by Vite)
        $themeJsonPath = $publicPath.'/build/assets/theme.json';
        if (file_exists($themeJsonPath)) {
            $result['theme_json'] = json_decode(file_get_contents($themeJsonPath), true);
        }

        // Get asset URLs
        $result['base_url'] = get_stylesheet_directory_uri().'/public/build/';

        return Response::json($result);
    }
}
